name: MetabWorkflowTutorial
channels:
  - defaults
  - conda-forge
  - cimcb
dependencies:
  - python=3.7.3
  - jupyter=1.0.0
  - notebook=6.4.7
  - bokeh=1.1.0
  - numpy=1.16.3
  - pandas=0.24.2
  - openpyxl=2.6.1
  - cimcb_lite=1.0.3
  - xlrd=1.2.0
  - Jinja2==3.0.3
